baseurl = "https://hoshinotsuyoshi.com/"
theme = "casper-two"
languageCode = "ja-jp"
paginate = 20

[params]
  title       = "hoshinotsuyoshi.com"
  subtitle    = "hoshinotsuyoshi.com - è‡ªç”±ãªãƒ–ãƒ­ã‚°ã ã‚ˆ"
  # cover       = "images/snoopy_donuts.jpg"
  description = "hoshinotsuyoshiã®è‡ªç”±ãªãƒ–ãƒ­ã‚°ã€‚rubyã¨ã‹dockerã¨ã‹ã®è©±é¡Œã‚’æ›¸ããŸã„ã€‚keyboard, vimã¨ã‹æ—¥å¸¸ã®è©±é¡Œã‚‚ã€‚"
  metaDescription = "hoshinotsuyoshiã®è‡ªç”±ãªãƒ–ãƒ­ã‚°ã€‚rubyã¨ã‹dockerã¨ã‹ã®è©±é¡Œã‚’æ›¸ããŸã„ã€‚keyboard, vimã¨ã‹æ—¥å¸¸ã®è©±é¡Œã‚‚ã€‚"
  googleAnalytics = "UA-87800718-1"
  customCSS = ["/css/prism.css"]
  RSSLink = ""

  twitterName = "hoppiestar"
  fbName = "tsuyoshi.hoshino"
  githubName = "hoshinotsuyoshi"

  logo = "images/hoshinotsuyoshi.png"
  # logo = "hugo-logo.png"
  # orgName = ""
  # orgWebsite = ""
  # orgDescription = ""

  author = "hoshinotsuyoshi"
  authorAvatar = "images/hoshinotsuyoshi.png"
  authorLocation = "Tokyo, Japan"
  authorWebsite = "https://hoshinotsuyoshi.com"
  authorDescription = "æ˜Ÿé‡å‰›å¿—(ã»ã—ã®ã¤ã‚ˆã—) web application engineer. ruby/rails/docker"

  pageNotFoundTitle = "404 - Page not found"

  # casper or caspertwo
  singleViewStyle = "casper"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "vimâš¡"
  url = "/tags/vim/"
  weight = 93

[[menu.main]]
  name = "RubyğŸ’"
  url = "/tags/ruby/"
  weight = 100

[[menu.main]]
  name = "RailsğŸšƒ"
  url = "/tags/rails/"
  weight = 98
